[workspace]
members = ["core", "core/prisma", "apps/cli"]

[patch.crates-io]
rspc = { git = "https://github.com/oscartbeaumont/rspc.git" }
specta = { git = "https://github.com/oscartbeaumont/rspc.git" }
