// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"api/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/shorturl/shorten",
				Handler: ShorturlShortenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/shorturl/expand",
				Handler: ShorturlExpandHandler(serverCtx),
			},
		},
	)
}
