// Code generated by goctl. DO NOT EDIT!
// Source: shorturl.proto

package server

import (
	"context"

	"api/rpc/shorturl/internal/logic"
	"api/rpc/shorturl/internal/svc"
	"api/rpc/shorturl/shorturl"
)

type TransformerServer struct {
	svcCtx *svc.ServiceContext
	shorturl.UnimplementedTransformerServer
}

func NewTransformerServer(svcCtx *svc.ServiceContext) *TransformerServer {
	return &TransformerServer{
		svcCtx: svcCtx,
	}
}

func (s *TransformerServer) Expand(ctx context.Context, in *shorturl.ExpandReq) (*shorturl.ExpandResp, error) {
	l := logic.NewExpandLogic(ctx, s.svcCtx)
	return l.Expand(in)
}

func (s *TransformerServer) Shorten(ctx context.Context, in *shorturl.ShortenReq) (*shorturl.ShortenResp, error) {
	l := logic.NewShortenLogic(ctx, s.svcCtx)
	return l.Shorten(in)
}
