// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amaQuestionsFieldNames          = builder.RawFieldNames(&AmaQuestions{}, true)
	amaQuestionsRows                = strings.Join(amaQuestionsFieldNames, ",")
	amaQuestionsRowsExpectAutoSet   = strings.Join(stringx.Remove(amaQuestionsFieldNames, "id", "create_time", "update_time"), ",")
	amaQuestionsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(amaQuestionsFieldNames, "id", "create_time", "update_time"))

	cachePublicAmaQuestionsIdPrefix = "cache:public:amaQuestions:id:"
)

type (
	amaQuestionsModel interface {
		Insert(ctx context.Context, data *AmaQuestions) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmaQuestions, error)
		Update(ctx context.Context, data *AmaQuestions) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmaQuestionsModel struct {
		sqlc.CachedConn
		table string
	}

	AmaQuestions struct {
		Id        int64     `db:"id"`
		Question  string    `db:"question"`
		CreatedAt time.Time `db:"created_at"`
	}
)

func newAmaQuestionsModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultAmaQuestionsModel {
	return &defaultAmaQuestionsModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."ama_questions"`,
	}
}

func (m *defaultAmaQuestionsModel) Insert(ctx context.Context, data *AmaQuestions) (sql.Result, error) {
	publicAmaQuestionsIdKey := fmt.Sprintf("%s%v", cachePublicAmaQuestionsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, amaQuestionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Question, data.CreatedAt)
	}, publicAmaQuestionsIdKey)
	return ret, err
}

func (m *defaultAmaQuestionsModel) FindOne(ctx context.Context, id int64) (*AmaQuestions, error) {
	publicAmaQuestionsIdKey := fmt.Sprintf("%s%v", cachePublicAmaQuestionsIdPrefix, id)
	var resp AmaQuestions
	err := m.QueryRowCtx(ctx, &resp, publicAmaQuestionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", amaQuestionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmaQuestionsModel) Update(ctx context.Context, data *AmaQuestions) error {
	publicAmaQuestionsIdKey := fmt.Sprintf("%s%v", cachePublicAmaQuestionsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, amaQuestionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.Question, data.CreatedAt)
	}, publicAmaQuestionsIdKey)
	return err
}

func (m *defaultAmaQuestionsModel) Delete(ctx context.Context, id int64) error {
	publicAmaQuestionsIdKey := fmt.Sprintf("%s%v", cachePublicAmaQuestionsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicAmaQuestionsIdKey)
	return err
}

func (m *defaultAmaQuestionsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicAmaQuestionsIdPrefix, primary)
}

func (m *defaultAmaQuestionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", amaQuestionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmaQuestionsModel) tableName() string {
	return m.table
}
