import type { NextPage } from 'next';
import Head from 'next/head';

import { trpc } from '@/utils/trpc';

const Finance: NextPage = () => {
  // const expenses = trpc.proxy.finance.findManyExpense.useQuery({});

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flex flex-col items-center justify-center min-h-screen p-4 mx-auto">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Create <span className="text-purple-300">T3</span> App
        </h1>
      </main>
    </>
  );
};

export default Finance;
